"""rename address

Revision ID: c00bcde6f9ec
Revises: d94ee2139b03
Create Date: 2024-04-21 18:08:09.079433

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "c00bcde6f9ec"
down_revision = "d94ee2139b03"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("departments", "address", new_column_name="location")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("departments", "location", new_column_name="address")
    # ### end Alembic commands ###
