"""rename department

Revision ID: d94ee2139b03
Revises: f3fc66e61d10
Create Date: 2024-04-21 18:05:40.216307

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "d94ee2139b03"
down_revision = "f3fc66e61d10"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table("department", "departments")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table("departments", "department")
    # ### end Alembic commands ###
